name: deploy_pr

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run test:unit

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm version '${{ github.event.number }}.${{ github.run_number }}.0' --no-git-tag-version
      - run: npm run build
      - run: |
          echo @GPortas:registry=https://npm.pkg.github.com >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc
      - run: npm view
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --tag 'PR-${{ github.event.number }}-${{ github.run_number }}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
