name: deploy_to_github

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run test:unit

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/
      - run: npm version '${ PR_NUMBER }.0.0' --no-git-tag-version
      - run: npm ci
      - run: |
          echo @GPortas:https://npm.pkg.github.com/ >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${ NPM_TOKEN }' >> .npmrc
      - run: npm publish --tag ${{ github.head_ref }}
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
